export const PERMISSIONS = Object.freeze({
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DEACTIVATE: "users.deactivate",
  INVENTORY_READ: "inventory.read",
  INVENTORY_CREATE: "inventory.create",
  INVENTORY_UPDATE: "inventory.update",
  INVENTORY_MOVE: "inventory.move",
  SALES_READ: "sales.read",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_CANCEL: "sales.cancel",
  SALES_PRODUCTS_READ: "sales.products.read",
  SALES_PRODUCTS_MANAGE: "sales.products.manage",
  AUDIT_READ: "audit.read",
  ANALYTICS_READ: "analytics.read",
  CASH_OPEN: "cash.open",
  CASH_CLOSE: "cash.close",
})
