spring.application.name=mlbt-spring-web

server.port=8082

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mlbt_ga7_aa3_ev01?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

logging.level.org.hibernate.SQL=DEBUG
